name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build php73 --file Dockerfile --tag laravolt/php73-toolset:$(date +%s)
